### PR TITLE
Add book list for user profile and link navigation from BookListComponent to Bookprofile

### PR DESCRIPTION
**Pull request by LeniCadorinEpfl**
### Summary 
This PR  adds the BookListComponent in the `UserProfile` screen and enables navigation from the `BookListComponent` to the corresponding `BookProfile` screen when clicking on a book. These changes enhance the UX by providing a way to browse and navigate through the user's book collection.

### Key Changes
**1. `BookListComponent` Integration in `UserProfile`:**
- Added the `BookListComponent` to the `UserProfile` screen to display a user's list of books.
- Implemented a loading indicator (CircularProgressIndicator) and a fallback message when no books are available.

**2. Navigation Support:**
- Integrated navigation from the `BookListComponent` to the corresponding `BookProfile` screen.
- Used `NavigationActions` to handle deep links with the bookId as a parameter.

**3. Updates Across Modules:**
- Adjusted tests in `BookDisplayComponentTest`, `UserProfileScreenTest`, and `OthersUserProfileTest` to cover the new navigation logic and ensure functionality.
- Updated the `MainActivity` navigation graph to include the `BookProfile` route with a bookId parameter.

**4. Reusability Improvements:**
- Enhanced `BookListComponent` by adding an onBookClick callback to facilitate navigation.
- Updated code in many part such ad in the Map DraggableMenu or the `OthersUserProfileScreen` to leverage the enhanced BookListComponent for consistent behavior.

### Testing
**Unit Tests:**
  - Verified that clicking on a book in the BookListComponent correctly navigates to the BookProfile.

The tests for the UserProfile Screen to verify that the BookListComponent is displayed correctly are currently missing. I spent 4 hours working on them, and they are scheduled to be added next week.

### UI Visual Representation:
image

### CODE REVIEW

**Comment by LeniCadorinEpfl** [comment]
The code coverage is pretty normal, as I spent more than 4 hours on trying to add tests on the `BookListComponent` in the `UserProfileScreenTest`. Unfortunately, I wasn't able to get it working. When launching the tests when I looked at the log the output of the user booklist  had `BookListUIID[with 2 valid UUID]` but then when the book where were being fetched, the output, the mutable list containing the DataBook was empty although in the test I have an:  _every getbook( with any() parameters) return the testbooks_ . So I am really not sure why this is happening.
Additionally, there’s an issue with the tests in the `MapScreenTest`, where the TestTag for the `BookListComponent` doesn’t seem to work, despite the `BookListComponent` being visible during the test.
I will look more into it next week, to be able fix this.

**Comment by TheoSchlaeppi** [comment]
I watch your code and it's good but as you mention on your comment you will need to fix the test. I think it's better for the project to let this branch up so you can see what is the problem with it.

**Comment by LeniCadorinEpfl** [comment]
Both issues with the tests have been resolved :)

**Review by TheoSchlaeppi — APPROVED** [review]
Thank you for this PR! I really appreciate the work you’ve done here. These features were essential for the proper functioning of our application, and you’ve implemented them perfectly. The tests are thorough and work as expected, and the code is well-written. I don’t see any areas for improvement. From my perspective, these additions are fully approved!

**Pull request merged**
