### PR TITLE
Enhance UserProfileScreen UI

### PR DESCRIPTION
**Pull request by LeniCadorinEpfl**
This PR introduces significant improvements to the UserProfileScreen UI to enhance usability and visual appeal. The changes focus on better structuring the profile information and aligning key UI components like the profile picture, edit button, and supporting layout elements.

#### 1. Added Top and Bottom App Bars:
  - Integrated `TopAppBar` with a screen title and profile button.
  - Integrated the `BottomAppBar` in the `UserProfileScreen`.

#### 2. Refactored User Profile Layout:
  - Aligned the EditButton with the profile picture for consistent placement.
  - Improved layout hierarchy for user details : name, email, phone and address.
  - Introduced labeled text components to standardize the presentation of user information.

#### 3. Reusable Components:
  - Created a new `LabeledTextUserProfile` composable for consistent and modularized text-field display.

#### Updated Test :
  - Added tests for `TopAppBar` visibility and functionality using composeTestRule.
  - Ensured proper tagging for all UI elements to maintain testability and consistency.

### UI Visual Representation:
Screenshot 2024-12-08 180000

### CODE REVIEW

**Review by oliveja22 — CHANGES_REQUESTED** [review]
Overall the pull request is very good and has few issues if any, I therefore must commend you for your work. There is but one minute detail I would allow myself to mention, while requesting changes of course; that is the fact that there are a number of hardcoded values, which are not repeated, but are hardcoded nonetheless. Examples are the spacer size on line 228, or the image size on line 203. Much like you have done below for the `LabeledTextUserProfile`, it would be nice to have the important ones at the very least as variables that are more easily modified. This would include object sizes and spacer sizes, although I do not find it necessary to do the same for padding. Additionally and lastly, on line 219, you add a padding of what seems to be 0; do correct me if I am wrong in this however. Overall it is an incredibly good pull request, but I feel like I can nontheless ask for these few changes that should take no more than 5 minutes to ensure that if we ever want to modify those values, it is easier, and it is also more consistent as you have done this elsewhere in the file.

**Comment by LeniCadorinEpfl** [comment]
Thank you very much for you review. Regarding the constants part, this is not my code. I just added the alignment in the UserProfileScreen for the EditButton and the profile picture. And I also added the LabeledTextUserProfile code for a nice visual representation of the user's information, the other part was done by Gregory in previous PR. That said, I’m happy to refactor the hardcoded values into constants to improve the overall quality.

**Review by oliveja22 — APPROVED** [review]
Thank you for your comment, I did not realise what I asked for was not of your own doing, given that, I would love it if you could change it. Nonetheless, given that it is not your work, I will simply approve it now.

**Comment by Chocolat2** [comment]
image
👌

**Pull request merged**
